In [3]:
import json
import pandas as pd

INPUT_PATH = "../../data/raw/steam_apps.json"

with open(INPUT_PATH, "r", encoding="utf-8") as file:
    data = json.load(file)

apps = data["response"]["apps"]

df = pd.DataFrame(apps)

print(df.head())
print()
print(df.shape)
print()
print(df.info())

   appid                       name  last_modified  price_change_number
0     10             Counter-Strike     1745368572             37149137
1     20      Team Fortress Classic     1745368565             37149137
2     30              Day of Defeat     1745368580             37149137
3     40         Deathmatch Classic     1745368570             37149137
4     50  Half-Life: Opposing Force     1745368539             37149137

(1000, 4)

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   appid                1000 non-null   int64
 1   name                 1000 non-null   str
 2   last_modified        1000 non-null   int64
 3   price_change_number  1000 non-null   int64
dtypes: int64(3), str(1)
memory usage: 31.4 KB
None

In [4]:
print(df.columns)
print(df.dtypes)
print(df.isna().sum())
print(df.duplicated().sum())
print(df["appid"].duplicated().sum())

Index(['appid', 'name', 'last_modified', 'price_change_number'], dtype='str')
appid                  int64
name                     str
last_modified          int64
price_change_number    int64
dtype: object
appid                  0
name                   0
last_modified          0
price_change_number    0
dtype: int64
0
0

In [5]:
print(df["name"].nunique())

999

In [6]:
print(df.describe(include="all"))

               appid                name  last_modified  price_change_number
count    1000.000000                1000   1.000000e+03         1.000000e+03
unique           NaN                 999            NaN                  NaN
top              NaN  Fallout: New Vegas            NaN                  NaN
freq             NaN                   2            NaN                  NaN
mean    26498.779000                 NaN   1.678159e+09         3.557934e+07
std     18063.158425                 NaN   1.095387e+08         6.580231e+06
min        10.000000                 NaN   1.447351e+09         0.000000e+00
25%     10127.500000                 NaN   1.601850e+09         3.714914e+07
50%     24600.000000                 NaN   1.726579e+09         3.800429e+07
75%     40125.000000                 NaN   1.763466e+09         3.886868e+07
max     67370.000000                 NaN   1.790285e+09         3.917414e+07

In [7]:
df[df["name"].duplicated(keep=False)]

     appid                name  last_modified  price_change_number
471  22380  Fallout: New Vegas     1765992876             38004287
473  22490  Fallout: New Vegas     1765992922             38004287

In [12]:
# make sure all appids are positive
df[df["appid"] <= 0]

# blank names 
df[df["name"].str.strip() == ""]

Empty DataFrame
Columns: [appid, name, last_modified, price_change_number]
Index: []

In [ ]:
# datetime conversion
pd.to_datetime(df["last_modified"], unit="s")

0     2025-04-23 00:36:12
1     2025-04-23 00:36:05
2     2025-04-23 00:36:20
3     2025-04-23 00:36:10
4     2025-04-23 00:35:39
              ...
995   2026-09-14 17:45:05
996   2020-04-22 19:37:57
997   2024-08-22 15:42:32
998   2019-05-17 01:45:15
999   2024-10-11 19:25:15
Name: last_modified, Length: 1000, dtype: datetime64[s]

In [ ]:
# pricechange distribution
df["price_change_number"].value_counts().head(10)

price_change_number
37149137    207
38969706    115
26388145     70
39170682     52
38868678     51
38672960     49
29222913     37
39068877     29
38004287     23
38290664     21
Name: count, dtype: int64